import { StyleSheet } from 'react-native';

import { palette } from '@/src/shared/components/ui/palette';

export const styles = StyleSheet.create({
  actions: {
    backgroundColor: palette.background,
    gap: 12,
    padding: 24,
  },
  content: {
    gap: 20,
    padding: 24,
    paddingTop: 32,
  },
  details: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 0,
    paddingHorizontal: 20,
    paddingVertical: 4,
    boxShadow: '0px 8px 16px rgba(21, 51, 95, 0.06)',
    elevation: 2,
  },
  blockRow: {
    borderBottomColor: palette.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 8,
    paddingVertical: 16,
  },
  blockValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 21,
  },
  label: {
    color: palette.textSoft,
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  hero: {
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  heroText: {
    flex: 1,
  },
  loading: {
    color: palette.muted,
    fontSize: 15,
    textAlign: 'center',
  },
  logoRow: {
    borderBottomColor: palette.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
    paddingVertical: 16,
  },
  logoCard: {
    alignItems: 'center',
    backgroundColor: palette.surfaceMuted,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    padding: 16,
    boxShadow: '0px 6px 12px rgba(21, 51, 95, 0.05)',
    elevation: 1,
  },
  row: {
    alignItems: 'flex-start',
    borderBottomColor: palette.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 16,
    paddingVertical: 16,
  },
  subtitle: {
    color: palette.muted,
    fontSize: 15,
    marginTop: 4,
  },
  skeleton: {
    gap: 20,
  },
  skeletonDetails: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  skeletonHero: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 18,
  },
  skeletonLabel: {
    backgroundColor: palette.disabled,
    borderRadius: 6,
    height: 14,
    width: '36%',
  },
  skeletonRow: {
    borderBottomColor: palette.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  skeletonSubtitle: {
    backgroundColor: palette.disabled,
    borderRadius: 6,
    height: 14,
    width: '46%',
  },
  skeletonTitle: {
    backgroundColor: palette.disabled,
    borderRadius: 6,
    height: 28,
    width: '64%',
  },
  skeletonValue: {
    backgroundColor: palette.disabled,
    borderRadius: 6,
    height: 14,
    width: '42%',
  },
  title: {
    color: palette.text,
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
  },
  value: {
    color: palette.text,
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'right',
  },
});
